config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  
  get '/home/about', to: 'home#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "friends#index"
   #get '/users/sign_out', to: 'devise#sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  
  belongs_to :user


  validates :first_name, :last_name, :email ,presence: true

  def to_s
  	str="#{first_name.capitalize} #{last_name.capitalize}"
  	return str
  	#friend.first_name +  friend.last_name 
  end


end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :friends

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user,only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)


    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice:"not autherized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        
      </ul>
    </div>
  <% end %>
<br/>
  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name,class:"form-control",placeholder: "First Name" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name,class:"form-control",placeholder: "Last Name" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email,class:"form-control" ,placeholder: "Email"%>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,class:"form-control",placeholder: "Phone"%>
  </div>

  <div class="form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter ,class:"form-control",placeholder: "Twitter"%>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id ,id: :friend_user_id,class:"form-control",value: current_user.id,type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<br/><h1>Editing friend</h1>


<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend ,class:"btn btn-outline-secondary"%> |
  <%= link_to "Back to friends", friends_path,class:"btn btn-outline-dark" %>
</div>

app/views/friends/index.html.erb
<%if user_signed_in? %>
<br/>
<table class="table table-bordered  table-hover">
  <thead >
    <tr class="table-info">
      <th>Full Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User Id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<div id="friends">
  <% @friends.each do |friend| %>
  <%if friend.user == current_user %>
    <tr class="table-primary" >
      <th><%=link_to friend.to_s, friend_path(friend) %></th>
      <th><%= friend.email %></th>
      <th><%= friend.phone %></th>
      <th><%= friend.twitter %></th>
      <th><%= friend.user_id %></th>
      <th><%= link_to "Delete", friend, method: :delete , data:{ confirm: "are you sure" },class: "btn btn-outline-danger btn-sm"%></th>
    
    </tr>
    <% end %>
    <% render friend %>
    

  <% end %>
  <p>
      
  </p>

</div>
</tbody>
</table>
<br/>
<%= link_to "New friend", new_friend_path ,class:"btn btn-outline-primary"%>

<%else%>
  <%= render 'layouts/index'%>

<%end%>

app/views/friends/new.html.erb
<br/>
<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path ,class:"btn btn-outline-secondary"%>
</div>

app/views/friends/show.html.erb
<% render @friend %>
<br/>

<div>
  <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @friend.to_s %></h1>
    <br/>
      <hr class="my-4">

    <p class="lead"><%= @friend.email %></p>
     <p class="lead"> <%= @friend.phone %></p>
      <p class="lead">     <%= @friend.twitter %>
    </p>

  </div>
  <div>
  <%= link_to "Edit this friend", edit_friend_path(@friend),class: "btn btn-outline-secondary" %> |
  <%= link_to "Back to friends", friends_path , class: "btn btn-outline-dark"%>

  </div>
  <br/>
    <%= button_to "Destroy this friend", @friend, method: :delete , notice: "are you sure",class: "btn  btn-outline-danger"%>

</div>

</div>

app/views/home/_header.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

    <div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      	<%= link_to 'Friends App', root_path , class: "navbar-brand"%>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
          	<%= link_to "About", home_about_path, class: "nav-link" %>
            <span class="sr-only">(current)</span>
          </li>
          <% if user_signed_in? %>

            <li class="nav-item">                                                                             
               <%= link_to "Friend", friends_path, class: "nav-link" %>
            </li>

            <li class="nav-item">                                                                             
               <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
            </li>
 
                <li class="nav-item">                                                                             
                  <%= link_to "Sign Out", destroy_user_session_path,method: :delete, class: "nav-link" %>
                </li>
                <li class="nav-item">                                                                             
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
                 </li>

          <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">                                                                             
                <%= link_to "Sign In", user_session_path, class: "nav-link" %>
              </li>
          <% end %>
        
        </ul>
      </div>
      </nav>
    </div>
</body>
</html>

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>


    <div>
    	<div class="container my-5">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
      <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
        <h1 class="display-4 fw-bold lh-1">Add your friends details now!!</h1>
        <p class="lead">This Website is build to add your friends details ..any one can use to add friends to their accounts ..You acn also Add the personal information of your friend like contact number,email,twitter.Keep it private using the authentication </p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <%= link_to "Sign up", new_user_registration_path(@resource_name) ,class:"btn  btn-outline-primary" %> | 
        <%= link_to "Log in", user_session_path(@resource_name) ,class:"btn btn-outline-dark"%><br />
        </div>
      </div>
      <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
           <%= image_tag "2.jpg", height: 300 %>

      </div>
    </div>
  </div>

    </div>
</div>
</body>
</html>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h2>heyyy welcome here</h2>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_index.html.erb
<br/><center><h2>Friends Forever</h2></center><br/>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
		<%= image_tag "4.jpg", height: 700 ,class:"d-block w-100"%>    
	</div>
    <div class="carousel-item">
		<%= image_tag "5.jpg", height: 700 ,class:"d-block w-100"%>
    </div>
    <div class="carousel-item">
		<%= image_tag "6.jpg", height: 700 ,width:700,class:"d-block w-100"%>    
	</div>
  </div>
 <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Friends</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
      <br/>
        <%= render 'layouts/alerts'%>
      <% end %>

      <%= yield %>

    </div>
    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>